# 配置内容详见：PodConfigs/config_podspec.rb
require_relative "PodConfigs/config_podspec.rb"

# Uncomment the next line to define a global platform for your project
platform :ios, YXConfig.deployment_target
source 'https://github.com/CocoaPods/Specs.git'

target 'app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # 基础库
  pod 'NIMSDK_LITE', '10.9.76'
  pod 'NECoreKit', '9.8.1'
  pod 'NECoreIM2Kit/NOS_Special', '1.1.7'
  pod 'NECommonKit', '9.7.6'
  pod 'NECommonUIKit', '9.8.3'
  pod 'NEChatKit/NOS_Special', YXConfig.imuikit_version
  
  # UI 组件，YXConfig.imuikit_version = 10.9.0
  pod 'NEChatUIKit/NOS_Special', YXConfig.imuikit_version               # 会话（聊天）组件
  pod 'NEContactUIKit/NOS_Special', YXConfig.imuikit_version            # 通讯录组件
  pod 'NEConversationUIKit/NOS_Special', YXConfig.imuikit_version       # (云端)会话列表组件
  pod 'NELocalConversationUIKit/NOS_Special', YXConfig.imuikit_version  # (本地)会话列表组件
  pod 'NETeamUIKit/NOS_Special', YXConfig.imuikit_version               # 群相关设置组件

  # 扩展库 - 呼叫组件
  pod 'NERtcSDK/RtcBasic'                   #  RTC 音视频基础组件
  pod 'NERtcSDK/Nenn'                       #  RTC 音视频神经网络组件（使用背景虚化功能需要集成）
  pod 'NERtcSDK/Segment'                    #  RTC 音视频背景分割组件（使用背景虚化功能需要集成）
  pod 'NERtcCallKit/NOS_Special', '4.1.0'
  pod 'NERtcCallUIKit/NOS_Special', '4.1.0' # (源码地址：https://github.com/netease-kit/NEVideoCall-1to1/tree/main/NLiteAVDemo-iOS-ObjC/CallKit)
  
  # 可选 - 图片选择库
  pod 'ZLPhotoBrowser'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = YXConfig.deployment_target
      
      # Apple 芯片模拟器运行打开以下代码
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
